package com.gramaurja.utils

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf

private val LocalLanguageCode = compositionLocalOf { "en" }

@Composable
fun AppLanguageProvider(
    languageCode: String,
    content: @Composable () -> Unit
) {
    CompositionLocalProvider(
        LocalLanguageCode provides if (languageCode.isBlank()) "en" else languageCode,
        content = content
    )
}

@Composable
fun t(key: String): String = translate(LocalLanguageCode.current, key)

private fun translate(lang: String, key: String): String {
    val map = when (lang) {
        "kn" -> kannada
        "hi" -> hindi
        else -> english
    }
    return map[key] ?: english[key] ?: key
}

private val english = mapOf(
    "app_name" to "Grama-Urja",
    "home" to "Home",
    "pump" to "Pump",
    "reports" to "Reports",
    "analytics" to "Analytics",
    "profile" to "Profile",
    "alerts" to "Alerts",
    "choose_language" to "Choose Language",
    "selected" to "Selected",
    "tap_continue" to "Tap to continue",
    "sign_in" to "Sign In",
    "create" to "Create Account",
    "create_account" to "Create Account",
    "sign_in_title" to "Sign In",
    "create_subtitle" to "Create one account and track your local power line.",
    "signin_subtitle" to "Open your local energy dashboard.",
    "phone_number" to "Phone Number",
    "full_name" to "Full Name",
    "password" to "Password",
    "confirm_password" to "Confirm Password",
    "continue" to "Continue",
    "select_location" to "Select Location",
    "search_location" to "Search district or village",
    "continue_selected_location" to "Continue",
    "dashboard" to "Dashboard",
    "power_status" to "Power Status",
    "last_updated" to "Last Updated",
    "quick_action" to "Quick Action",
    "power_on" to "Power ON",
    "power_off" to "Power OFF",
    "outages_today" to "Outages Today",
    "recent_updates" to "Recent Updates",
    "pump_timer" to "Pump Timer",
    "crop_type" to "Crop Type",
    "motor_hp" to "Motor HP",
    "water_requirement" to "Water Requirement",
    "calculate" to "Calculate",
    "report_issue" to "Report Issue",
    "issue_type" to "Issue Type",
    "description" to "Description",
    "upload_images" to "Upload Images",
    "submit" to "Submit",
    "saved_reports" to "Saved Reports",
    "history_analytics" to "History & Analytics",
    "status_table" to "Status Table",
    "current_status" to "Current Status",
    "total_updates" to "Total Updates",
    "date" to "Date",
    "status" to "Status",
    "time" to "Time",
    "zone" to "Transformer Zone",
    "dark_theme" to "Dark Theme",
    "change_zone" to "Change Zone",
    "logout" to "Logout",
    "hero_title" to "Reliable Village Power",
    "hero_subtitle" to "Track zone updates and take action faster.",
    "recommended_runtime" to "Recommended runtime",
    "status_now" to "Status Now",
    "zone_updates" to "Zone Updates",
    "upload_button" to "Upload",
    "image_added" to "Image added",
    "alerts_summary" to "Alert Summary",
    "warnings" to "Warnings",
    "activity" to "Activity",
    "tagline" to "Community Powered Energy Updates",
    "community_alert_center" to "Community alert center",
    "alerts_subtitle" to "Track feeder warnings and recent local power activity in one place.",
    "stored_warning_messages" to "Stored warning messages",
    "needs_field_attention" to "Needs field attention",
    "latest_feeder_state" to "Latest feeder state",
    "power_off_events_today" to "Power OFF events today",
    "recent_timeline" to "Recent timeline",
    "remember_me" to "Remember me",
    "forgot_password" to "Forgot Password?",
    "reset_password" to "Reset Password",
    "zone_required" to "Zone required",
    "signin_header_copy" to "Sign in to billing, stock, and analytics for your village power network.",
    "create_header_copy" to "Create your local account and start sharing feeder updates.",
    "reset_header_copy" to "Verify your saved account details and set a new password.",
    "signin_card_copy" to "Manage your feeder activity with quick local access.",
    "create_card_copy" to "Create your local account and start sharing feeder updates.",
    "reset_card_copy" to "Enter the registered phone number and transformer zone, then choose a new password.",
    "back_to_signin" to "Back to Sign In",
    "create_account_link" to "Create Account",
    "signin_footer_copy" to "Daily local insights, feeder health, and issue reporting in one place.",
    "create_footer_copy" to "Pick the exact feeder zone so reports, alerts, and updates stay relevant.",
    "reset_footer_copy" to "The entered phone number and transformer zone must match the stored local account.",
    "home_quick_action_copy" to "Post the latest feeder state for nearby farmers and households.",
    "useful_now" to "Useful now",
    "energy_tip_prefix" to "Energy tip:",
    "language_daily_use" to "Pick the language your village team will use every day.",
    "why_this_matters" to "Why this matters",
    "language_impact_copy" to "Alerts, power updates and field actions will appear in your chosen language across the app.",
    "profile_language" to "Choose language",
    "change_transformer_zone" to "Change transformer zone",
    "working_zone" to "Working zone",
    "change_zone_copy" to "This updates the app's current working transformer zone only. It does not change the logged-in profile card above.",
    "active_feeder_zones" to "Active feeder zones",
    "active_feeder_copy" to "This list shows only transformers whose latest status is ON.",
    "no_active_transformers" to "No active transformers",
    "version" to "Version",
    "pump_subtitle" to "Estimate irrigation runtime before starting the motor.",
    "runtime_guidance" to "Runtime guidance",
    "runtime_guidance_copy" to "Calculated from crop, motor HP and water need.",
    "load_meter" to "Load meter",
    "light_load" to "Light load",
    "moderate_load" to "Moderate load",
    "heavy_load" to "Heavy load",
    "light_load_copy" to "Short run. Suitable for quick watering cycles.",
    "moderate_load_copy" to "Balanced run. Monitor voltage during operation.",
    "heavy_load_copy" to "Long run. Check supply stability before starting.",
    "light" to "Light",
    "moderate" to "Moderate",
    "heavy" to "Heavy",
    "motor_input" to "Motor input",
    "horsepower_entered" to "Horsepower entered",
    "water_need" to "Water need",
    "requested_units" to "Requested units",
    "runtime_prefix" to "Runtime:",
    "reports_subtitle" to "Capture field issues fast so the local team can respond sooner.",
    "saved_offline" to "Saved offline",
    "reports_available_device" to "Reports available on this device",
    "add_fault_photo" to "Add a fault photo if available.",
    "weekly_outage_trends" to "Weekly outage trends"
)

private val kannada = english + mapOf(
    "app_name" to "ಗ್ರಾಮ-ಊರ್ಜಾ",
    "home" to "ಮುಖಪುಟ",
    "pump" to "ಪಂಪ್",
    "reports" to "ವರದಿಗಳು",
    "analytics" to "ವಿಶ್ಲೇಷಣೆ",
    "profile" to "ಪ್ರೊಫೈಲ್",
    "alerts" to "ಅಲರ್ಟ್‌ಗಳು",
    "choose_language" to "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    "selected" to "ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ",
    "tap_continue" to "ಮುಂದುವರಿಸಲು ತಟ್ಟಿರಿ",
    "sign_in" to "ಸೈನ್ ಇನ್",
    "create" to "ಖಾತೆ ರಚಿಸಿ",
    "create_account" to "ಖಾತೆ ರಚಿಸಿ",
    "sign_in_title" to "ಸೈನ್ ಇನ್",
    "create_subtitle" to "ಒಂದು ಖಾತೆ ರಚಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಸ್ಥಳೀಯ ವಿದ್ಯುತ್ ಮಾರ್ಗವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "signin_subtitle" to "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಎನರ್ಜಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯಿರಿ.",
    "phone_number" to "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    "full_name" to "ಪೂರ್ಣ ಹೆಸರು",
    "password" to "ಪಾಸ್ವರ್ಡ್",
    "confirm_password" to "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    "continue" to "ಮುಂದುವರಿಸಿ",
    "dashboard" to "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "quick_action" to "ತ್ವರಿತ ಕ್ರಿಯೆ",
    "power_on" to "ವಿದ್ಯುತ್ ಆನ್",
    "power_off" to "ವಿದ್ಯುತ್ ಆಫ್",
    "outages_today" to "ಇಂದಿನ ವ್ಯತ್ಯಯಗಳು",
    "recent_updates" to "ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳು",
    "pump_timer" to "ಪಂಪ್ ಟೈಮರ್",
    "crop_type" to "ಬೆಳೆ ಪ್ರಕಾರ",
    "motor_hp" to "ಮೋಟಾರ್ HP",
    "water_requirement" to "ನೀರಿನ ಅಗತ್ಯ",
    "calculate" to "ಲೆಕ್ಕಹಾಕಿ",
    "report_issue" to "ಸಮಸ್ಯೆ ವರದಿ",
    "issue_type" to "ಸಮಸ್ಯೆ ಪ್ರಕಾರ",
    "description" to "ವಿವರಣೆ",
    "upload_images" to "ಚಿತ್ರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    "submit" to "ಸಲ್ಲಿಸಿ",
    "saved_reports" to "ಉಳಿಸಿದ ವರದಿಗಳು",
    "history_analytics" to "ಇತಿಹಾಸ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ",
    "status_table" to "ಸ್ಥಿತಿ ಪಟ್ಟಿಕೆ",
    "current_status" to "ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ",
    "total_updates" to "ಒಟ್ಟು ನವೀಕರಣಗಳು",
    "date" to "ದಿನಾಂಕ",
    "status" to "ಸ್ಥಿತಿ",
    "time" to "ಸಮಯ",
    "zone" to "ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ವಲಯ",
    "logout" to "ಲಾಗ್ ಔಟ್",
    "hero_title" to "ನಂಬಬಹುದಾದ ಗ್ರಾಮ ವಿದ್ಯುತ್",
    "hero_subtitle" to "ವಲಯ ನವೀಕರಣಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಬೇಗ ಕ್ರಿಯೆಗೆಳಿಯಿರಿ.",
    "recommended_runtime" to "ಶಿಫಾರಸು ಮಾಡಿದ ಸಮಯ",
    "status_now" to "ಈಗಿನ ಸ್ಥಿತಿ",
    "zone_updates" to "ವಲಯ ನವೀಕರಣಗಳು",
    "upload_button" to "ಅಪ್ಲೋಡ್",
    "image_added" to "ಚಿತ್ರ ಸೇರಿಸಲಾಗಿದೆ",
    "alerts_summary" to "ಅಲರ್ಟ್ ಸಾರಾಂಶ",
    "warnings" to "ಎಚ್ಚರಿಕೆಗಳು",
    "activity" to "ಚಟುವಟಿಕೆ",
    "tagline" to "ಸಮುದಾಯ ಚಾಲಿತ ವಿದ್ಯುತ್ ನವೀಕರಣಗಳು",
    "community_alert_center" to "ಸಮುದಾಯ ಅಲರ್ಟ್ ಕೇಂದ್ರ",
    "alerts_subtitle" to "ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಫೀಡರ್ ಎಚ್ಚರಿಕೆ ಮತ್ತು ಇತ್ತೀಚಿನ ಸ್ಥಳೀಯ ವಿದ್ಯುತ್ ಚಟುವಟಿಕೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "stored_warning_messages" to "ಉಳಿಸಿದ ಎಚ್ಚರಿಕೆ ಸಂದೇಶಗಳು",
    "needs_field_attention" to "ಕ್ಷೇತ್ರ ಗಮನ ಅಗತ್ಯ",
    "latest_feeder_state" to "ಕೊನೆಯ ಫೀಡರ್ ಸ್ಥಿತಿ",
    "power_off_events_today" to "ಇಂದಿನ ವಿದ್ಯುತ್ ಆಫ್ ಘಟನೆಗಳು",
    "recent_timeline" to "ಇತ್ತೀಚಿನ ಸಮಯರೇಖೆ",
    "remember_me" to "ನನ್ನನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಿ",
    "forgot_password" to "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    "zone_required" to "ವಲಯ ಅಗತ್ಯ",
    "signin_header_copy" to "ನಿಮ್ಮ ಗ್ರಾಮೀಣ ವಿದ್ಯುತ್ ಜಾಲಕ್ಕಾಗಿ ಬಿಲ್ಲಿಂಗ್, ಸ್ಟಾಕ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಗಳಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    "create_header_copy" to "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಖಾತೆ ರಚಿಸಿ ಮತ್ತು ಫೀಡರ್ ನವೀಕರಣಗಳನ್ನು ಹಂಚಲು ಪ್ರಾರಂಭಿಸಿ.",
    "signin_card_copy" to "ತ್ವರಿತ ಸ್ಥಳೀಯ ಪ್ರವೇಶದೊಂದಿಗೆ ನಿಮ್ಮ ಫೀಡರ್ ಚಟುವಟಿಕೆಯನ್ನು ನಿರ್ವಹಿಸಿ.",
    "create_card_copy" to "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಖಾತೆ ರಚಿಸಿ ಮತ್ತು ಫೀಡರ್ ನವೀಕರಣಗಳನ್ನು ಹಂಚಲು ಪ್ರಾರಂಭಿಸಿ.",
    "back_to_signin" to "ಸೈನ್ ಇನ್‌ಗೆ ಹಿಂದಿರುಗಿ",
    "create_account_link" to "ಖಾತೆ ರಚಿಸಿ",
    "signin_footer_copy" to "ದೈನಿಕ ಸ್ಥಳೀಯ ಅಂತರ್ದೃಷ್ಟಿ, ಫೀಡರ್ ಆರೋಗ್ಯ ಮತ್ತು ಸಮಸ್ಯೆ ವರದಿ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.",
    "create_footer_copy" to "ಸರಿಯಾದ ಫೀಡರ್ ವಲಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ, ಅಲರ್ಟ್ ಮತ್ತು ನವೀಕರಣಗಳು ಸಂಬಂಧಿತವಾಗಿರಲಿ.",
    "home_quick_action_copy" to "ಹತ್ತಿರದ ಕೃಷಿಕರು ಮತ್ತು ಮನೆಗಳಿಗಾಗಿ ಕೊನೆಯ ಫೀಡರ್ ಸ್ಥಿತಿಯನ್ನು ಹಂಚಿ.",
    "useful_now" to "ಈಗ ಉಪಯುಕ್ತ",
    "energy_tip_prefix" to "ಊರ್ಜಾ ಸಲಹೆ:",
    "language_daily_use" to "ನಿಮ್ಮ ಗ್ರಾಮ ತಂಡ ದೈನಂದಿನವಾಗಿ ಬಳಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
    "why_this_matters" to "ಇದು ಯಾಕೆ ಮಹತ್ವದ್ದು",
    "language_impact_copy" to "ಅಲರ್ಟ್, ಪವರ್ ನವೀಕರಣಗಳು ಮತ್ತು ಕ್ಷೇತ್ರ ಕ್ರಿಯೆಗಳು ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಆಯ್ದ ಭಾಷೆಯಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.",
    "profile_language" to "ಭಾಷೆ ಆಯ್ಕೆ",
    "change_transformer_zone" to "ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ವಲಯ ಬದಲಾಯಿಸಿ",
    "working_zone" to "ಕಾರ್ಯ ವಲಯ",
    "change_zone_copy" to "ಇದು ಆಪ್‌ನ ಪ್ರಸ್ತುತ ಕಾರ್ಯ ವಲಯವನ್ನು ಮಾತ್ರ ನವೀಕರಿಸುತ್ತದೆ. ಮೇಲಿನ ಲಾಗಿನ್ ಪ್ರೊಫೈಲ್ ಕಾರ್ಡ್‌ಗೆ ಇದರಿಂದ ಬದಲಾವಣೆ ಆಗುವುದಿಲ್ಲ.",
    "active_feeder_zones" to "ಸಕ್ರಿಯ ಫೀಡರ್ ವಲಯಗಳು",
    "active_feeder_copy" to "ಈ ಪಟ್ಟಿಯಲ್ಲಿ ಕೊನೆಯ ಸ್ಥಿತಿ ON ಆಗಿರುವ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್‌ಗಳಷ್ಟೇ ಕಾಣುತ್ತವೆ.",
    "no_active_transformers" to "ಯಾವುದೇ ಸಕ್ರಿಯ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಇಲ್ಲ",
    "version" to "ಆವೃತ್ತಿ",
    "pump_subtitle" to "ಮೋಟಾರ್ ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು ನೀರಾವರಿ ಸಮಯವನ್ನು ಅಂದಾಜಿಸಿ.",
    "runtime_guidance" to "ಸಮಯ ಮಾರ್ಗದರ್ಶನ",
    "runtime_guidance_copy" to "ಬೆಳೆ, ಮೋಟಾರ್ HP ಮತ್ತು ನೀರಿನ ಅಗತ್ಯದ ಆಧಾರದ ಮೇಲೆ ಲೆಕ್ಕಿಸಲಾಗಿದೆ.",
    "load_meter" to "ಲೋಡ್ ಮೀಟರ್",
    "light_load" to "ಕಡಿಮೆ ಲೋಡ್",
    "moderate_load" to "ಮಧ್ಯಮ ಲೋಡ್",
    "heavy_load" to "ಭಾರಿ ಲೋಡ್",
    "light_load_copy" to "ಸಣ್ಣ ಓಟ. ಚಿಕ್ಕ ನೀರಾವರಿ ಚಕ್ರಗಳಿಗೆ ಸೂಕ್ತ.",
    "moderate_load_copy" to "ಸಮತೋಲಿತ ಓಟ. ಕಾರ್ಯಾಚರಣೆಯಲ್ಲಿ ವೋಲ್ಟೇಜ್ ಗಮನಿಸಿ.",
    "heavy_load_copy" to "ದೀರ್ಘ ಓಟ. ಆರಂಭಿಸುವ ಮೊದಲು ಸರಬರಾಜಿನ ಸ್ಥಿರತೆ ಪರಿಶೀಲಿಸಿ.",
    "light" to "ಕಡಿಮೆ",
    "moderate" to "ಮಧ್ಯಮ",
    "heavy" to "ಭಾರಿ",
    "motor_input" to "ಮೋಟಾರ್ ಇನ್‌ಪುಟ್",
    "horsepower_entered" to "ನಮೂದಿಸಿದ ಹಾರ್ಸ್‌ಪವರ್",
    "water_need" to "ನೀರಿನ ಅಗತ್ಯ",
    "requested_units" to "ಕೋರಿದ ಯೂನಿಟ್‌ಗಳು",
    "runtime_prefix" to "ಸಮಯ:",
    "reports_subtitle" to "ಕ್ಷೇತ್ರ ಸಮಸ್ಯೆಗಳನ್ನು ಬೇಗ ಸೆರೆ ಹಿಡಿದು ಸ್ಥಳೀಯ ತಂಡ ಬೇಗ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಸಹಾಯ ಮಾಡಿ.",
    "saved_offline" to "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
    "reports_available_device" to "ಈ ಸಾಧನದಲ್ಲಿರುವ ವರದಿಗಳು",
    "add_fault_photo" to "ಲಭ್ಯವಿದ್ದರೆ ದೋಷದ ಫೋಟೋ ಸೇರಿಸಿ.",
    "weekly_outage_trends" to "ವಾರಂತ್ಯದ ವ್ಯತ್ಯಯ ಧೋರಣೆಗಳು"
)

private val hindi = english + mapOf(
    "app_name" to "ग्राम-ऊर्जा",
    "home" to "होम",
    "pump" to "पंप",
    "reports" to "रिपोर्ट",
    "analytics" to "एनालिटिक्स",
    "profile" to "प्रोफाइल",
    "alerts" to "अलर्ट",
    "choose_language" to "भाषा चुनें",
    "selected" to "चुना गया",
    "tap_continue" to "आगे बढ़ने के लिए टैप करें",
    "sign_in" to "साइन इन",
    "create" to "खाता बनाएं",
    "create_account" to "खाता बनाएं",
    "sign_in_title" to "साइन इन",
    "create_subtitle" to "एक खाता बनाएं और अपनी स्थानीय बिजली लाइन ट्रैक करें.",
    "signin_subtitle" to "अपना स्थानीय ऊर्जा डैशबोर्ड खोलें.",
    "phone_number" to "फोन नंबर",
    "full_name" to "पूरा नाम",
    "password" to "पासवर्ड",
    "confirm_password" to "पासवर्ड पुष्टि करें",
    "continue" to "जारी रखें",
    "dashboard" to "डैशबोर्ड",
    "quick_action" to "त्वरित कार्य",
    "power_on" to "बिजली चालू",
    "power_off" to "बिजली बंद",
    "outages_today" to "आज की बाधाएं",
    "recent_updates" to "हाल के अपडेट",
    "pump_timer" to "पंप टाइमर",
    "crop_type" to "फसल प्रकार",
    "motor_hp" to "मोटर HP",
    "water_requirement" to "पानी की आवश्यकता",
    "calculate" to "गणना करें",
    "report_issue" to "समस्या रिपोर्ट करें",
    "issue_type" to "समस्या प्रकार",
    "description" to "विवरण",
    "upload_images" to "चित्र अपलोड करें",
    "submit" to "सबमिट",
    "saved_reports" to "सहेजी गई रिपोर्ट",
    "history_analytics" to "इतिहास और विश्लेषण",
    "status_table" to "स्थिति तालिका",
    "current_status" to "वर्तमान स्थिति",
    "total_updates" to "कुल अपडेट",
    "date" to "तारीख",
    "status" to "स्थिति",
    "time" to "समय",
    "zone" to "ट्रांसफार्मर ज़ोन",
    "logout" to "लॉग आउट",
    "hero_title" to "विश्वसनीय गांव बिजली",
    "hero_subtitle" to "ज़ोन अपडेट ट्रैक करें और जल्दी कार्रवाई करें.",
    "recommended_runtime" to "अनुशंसित समय",
    "status_now" to "अभी की स्थिति",
    "zone_updates" to "ज़ोन अपडेट",
    "upload_button" to "अपलोड",
    "image_added" to "चित्र जोड़ा गया",
    "alerts_summary" to "अलर्ट सारांश",
    "warnings" to "चेतावनियां",
    "activity" to "गतिविधि",
    "tagline" to "समुदाय संचालित ऊर्जा अपडेट",
    "community_alert_center" to "समुदाय अलर्ट केंद्र",
    "alerts_subtitle" to "एक ही जगह पर फीडर चेतावनियां और हाल की स्थानीय बिजली गतिविधि देखें.",
    "stored_warning_messages" to "सहेजे गए चेतावनी संदेश",
    "needs_field_attention" to "मैदानी ध्यान आवश्यक",
    "latest_feeder_state" to "नवीनतम फीडर स्थिति",
    "power_off_events_today" to "आज की बिजली बंद घटनाएं",
    "recent_timeline" to "हाल की समयरेखा",
    "remember_me" to "मुझे याद रखें",
    "forgot_password" to "पासवर्ड भूल गए?",
    "zone_required" to "ज़ोन आवश्यक",
    "signin_header_copy" to "अपने ग्रामीण बिजली नेटवर्क के बिलिंग, स्टॉक और एनालिटिक्स के लिए साइन इन करें.",
    "create_header_copy" to "अपना स्थानीय खाता बनाएं और फीडर अपडेट साझा करना शुरू करें.",
    "signin_card_copy" to "तेज स्थानीय एक्सेस के साथ अपनी फीडर गतिविधि संभालें.",
    "create_card_copy" to "अपना स्थानीय खाता बनाएं और फीडर अपडेट साझा करना शुरू करें.",
    "back_to_signin" to "वापस साइन इन",
    "create_account_link" to "खाता बनाएं",
    "signin_footer_copy" to "दैनिक स्थानीय जानकारी, फीडर हेल्थ और समस्या रिपोर्टिंग एक ही जगह पर.",
    "create_footer_copy" to "सही फीडर ज़ोन चुनें ताकि अलर्ट और अपडेट संबंधित रहें.",
    "home_quick_action_copy" to "नज़दीकी किसानों और परिवारों के लिए नवीनतम फीडर स्थिति पोस्ट करें.",
    "useful_now" to "अभी उपयोगी",
    "energy_tip_prefix" to "ऊर्जा सुझाव:",
    "language_daily_use" to "वह भाषा चुनें जिसे आपकी गांव टीम रोज़ इस्तेमाल करेगी.",
    "why_this_matters" to "यह क्यों महत्वपूर्ण है",
    "language_impact_copy" to "अलर्ट, पावर अपडेट और फील्ड एक्शन पूरे ऐप में आपकी चुनी हुई भाषा में दिखाई देंगे.",
    "profile_language" to "भाषा चुनें",
    "change_transformer_zone" to "ट्रांसफार्मर ज़ोन बदलें",
    "working_zone" to "कार्य ज़ोन",
    "change_zone_copy" to "यह केवल ऐप का वर्तमान कार्य ट्रांसफार्मर ज़ोन बदलता है. ऊपर दिख रहे लॉग-इन प्रोफाइल कार्ड पर इसका असर नहीं पड़ेगा.",
    "active_feeder_zones" to "सक्रिय फीडर ज़ोन",
    "active_feeder_copy" to "यह सूची केवल उन ट्रांसफार्मरों को दिखाती है जिनकी नवीनतम स्थिति ON है.",
    "no_active_transformers" to "कोई सक्रिय ट्रांसफार्मर नहीं",
    "version" to "संस्करण",
    "pump_subtitle" to "मोटर चालू करने से पहले सिंचाई समय का अनुमान लगाएं.",
    "runtime_guidance" to "रनटाइम मार्गदर्शन",
    "runtime_guidance_copy" to "फसल, मोटर HP और पानी की आवश्यकता के आधार पर गणना की गई है.",
    "load_meter" to "लोड मीटर",
    "light_load" to "हल्का लोड",
    "moderate_load" to "मध्यम लोड",
    "heavy_load" to "भारी लोड",
    "light_load_copy" to "छोटा रन. तेज सिंचाई चक्र के लिए उपयुक्त.",
    "moderate_load_copy" to "संतुलित रन. संचालन के दौरान वोल्टेज पर नज़र रखें.",
    "heavy_load_copy" to "लंबा रन. शुरू करने से पहले सप्लाई की स्थिरता जांचें.",
    "light" to "हल्का",
    "moderate" to "मध्यम",
    "heavy" to "भारी",
    "motor_input" to "मोटर इनपुट",
    "horsepower_entered" to "दर्ज हॉर्सपावर",
    "water_need" to "पानी की आवश्यकता",
    "requested_units" to "मांगी गई इकाइयां",
    "runtime_prefix" to "रनटाइम:",
    "reports_subtitle" to "फील्ड समस्याएं जल्दी कैप्चर करें ताकि स्थानीय टीम जल्दी प्रतिक्रिया दे सके.",
    "saved_offline" to "ऑफलाइन सहेजा गया",
    "reports_available_device" to "इस डिवाइस पर उपलब्ध रिपोर्ट",
    "add_fault_photo" to "उपलब्ध हो तो फॉल्ट फोटो जोड़ें.",
    "weekly_outage_trends" to "साप्ताहिक आउटेज रुझान"
)
